apiVersion: v1
kind: Service
metadata:
  name: cita-node-proxy-cluster-ip
  labels:
    app.kubernetes.io/component: cita-node-proxy
    {{- include "cita-node-proxy.labels" . | nindent 4 }}
spec:
  selector:
    app: cita-node-proxy
    {{- include "cita-node-proxy.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: proxy-server
      protocol: TCP
      port: 8080
      targetPort: 8080